// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Configitem is the predicate function for configitem builders.
type Configitem func(*sql.Selector)

// Servers is the predicate function for servers builders.
type Servers func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
