-- Create "casbin_rules" table
CREATE TABLE "casbin_rules" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "ptype" character varying NOT NULL,
  "v0" character varying NULL,
  "v1" character varying NULL,
  "v2" character varying NULL,
  "v3" character varying NULL,
  "v4" character varying NULL,
  "v5" character varying NULL,
  PRIMARY KEY ("id")
);
-- Create index "casbinrule_ptype" to table: "casbin_rules"
CREATE INDEX "casbinrule_ptype" ON "casbin_rules" ("ptype");
-- Create index "casbinrule_v0" to table: "casbin_rules"
CREATE INDEX "casbinrule_v0" ON "casbin_rules" ("v0");
-- Create index "casbinrule_v1" to table: "casbin_rules"
CREATE INDEX "casbinrule_v1" ON "casbin_rules" ("v1");
-- Create "configitems" table
CREATE TABLE "configitems" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "key" character varying NOT NULL,
  "value" character varying NOT NULL,
  "is_dynamic" boolean NOT NULL DEFAULT false,
  "project_id" bigint NULL,
  "status" character varying NOT NULL DEFAULT 'active',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "configitem_key" to table: "configitems"
CREATE UNIQUE INDEX "configitem_key" ON "configitems" ("key");
-- Create index "configitem_project_id" to table: "configitems"
CREATE INDEX "configitem_project_id" ON "configitems" ("project_id");
-- Create index "configitem_project_id_key" to table: "configitems"
CREATE INDEX "configitem_project_id_key" ON "configitems" ("project_id", "key");
-- Create index "configitem_status" to table: "configitems"
CREATE INDEX "configitem_status" ON "configitems" ("status");
-- Create index "configitems_key_key" to table: "configitems"
CREATE UNIQUE INDEX "configitems_key_key" ON "configitems" ("key");
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "uuid" uuid NOT NULL,
  "username" character varying NULL,
  "email" character varying NOT NULL,
  "password_hash" character varying NOT NULL,
  "nickname" character varying NULL,
  "avatar" character varying NULL,
  "phone" character varying NULL,
  "gender" smallint NOT NULL DEFAULT 0,
  "signature" character varying NULL,
  "status" smallint NOT NULL DEFAULT 1,
  "last_login_at" timestamptz NULL,
  "last_login_ip" character varying NULL,
  "timezone" character varying NOT NULL DEFAULT 'UTC',
  "language" character varying NOT NULL DEFAULT 'zh-CN',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "user_created_at" to table: "users"
CREATE INDEX "user_created_at" ON "users" ("created_at");
-- Create index "user_email" to table: "users"
CREATE UNIQUE INDEX "user_email" ON "users" ("email");
-- Create index "user_status" to table: "users"
CREATE INDEX "user_status" ON "users" ("status");
-- Create index "user_username" to table: "users"
CREATE UNIQUE INDEX "user_username" ON "users" ("username");
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Create index "users_uuid_key" to table: "users"
CREATE UNIQUE INDEX "users_uuid_key" ON "users" ("uuid");
-- Create "projects" table
CREATE TABLE "projects" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "uuid" character varying NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "status" smallint NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "owner_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "projects_users_owned_projects" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "project_created_at" to table: "projects"
CREATE INDEX "project_created_at" ON "projects" ("created_at");
-- Create index "project_owner_id" to table: "projects"
CREATE INDEX "project_owner_id" ON "projects" ("owner_id");
-- Create index "project_status" to table: "projects"
CREATE INDEX "project_status" ON "projects" ("status");
-- Create index "project_uuid" to table: "projects"
CREATE UNIQUE INDEX "project_uuid" ON "projects" ("uuid");
-- Create index "projects_uuid_key" to table: "projects"
CREATE UNIQUE INDEX "projects_uuid_key" ON "projects" ("uuid");
-- Create "project_members" table
CREATE TABLE "project_members" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role" character varying NOT NULL,
  "joined_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "project_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "project_members_projects_members" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "project_members_users_project_memberships" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "projectmember_project_id_user_id" to table: "project_members"
CREATE UNIQUE INDEX "projectmember_project_id_user_id" ON "project_members" ("project_id", "user_id");
-- Create index "projectmember_role" to table: "project_members"
CREATE INDEX "projectmember_role" ON "project_members" ("role");
-- Create index "projectmember_user_id" to table: "project_members"
CREATE INDEX "projectmember_user_id" ON "project_members" ("user_id");
-- Create "servers" table
CREATE TABLE "servers" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "ip" character varying NOT NULL,
  "user_servers" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "servers_users_servers" FOREIGN KEY ("user_servers") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "servers_ip_key" to table: "servers"
CREATE UNIQUE INDEX "servers_ip_key" ON "servers" ("ip");
