package testutils
package testutils

import (
	"context"
	"database/sql"


















































































































}	return nil	}		return fmt.Errorf("failed to drop test database: %w", err)	if err != nil {	_, err = db.Exec(fmt.Sprintf("DROP DATABASE IF EXISTS %s;", dbName))	defer db.Close()	}		return fmt.Errorf("failed to connect to postgres: %w", err)	if err != nil {	db, err := sql.Open("postgres", adminURL)	adminURL := "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"func DropTestDatabase(dbName string) error {// DropTestDatabase removes test database}	return nil	}		return fmt.Errorf("failed to create test database: %w", err)	if err != nil {	_, err = db.Exec(fmt.Sprintf("CREATE DATABASE %s;", dbName))	// Create new test database	_, _ = db.Exec(fmt.Sprintf("DROP DATABASE IF EXISTS %s;", dbName))	// Drop existing test database	defer db.Close()	}		return fmt.Errorf("failed to connect to postgres: %w", err)	if err != nil {	db, err := sql.Open("postgres", adminURL)	adminURL := "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"	// Connect to postgres database to create test DBfunc CreateTestDatabase(dbName string) error {// CreateTestDatabase creates a new test database (for parallel testing)}	require.NoError(t, err)	_, err = db.ExecContext(ctx, "SET session_replication_role = DEFAULT;")	// Re-enable triggers	}		}			t.Logf("Warning: failed to truncate table %s: %v", table, err)			// Log but don't fail if table doesn't exist		if err != nil {		_, err := db.ExecContext(ctx, query)		query := fmt.Sprintf("TRUNCATE TABLE %s CASCADE;", table)	for _, table := range tables {	}		"audit_logs",		"config_items",		"users",		"projects",		"casbin_rule",		"project_members",		"user_projects",	tables := []string{	// Truncate tables in order (respecting FK constraints)	require.NoError(t, err)	_, err := db.ExecContext(ctx, "SET session_replication_role = replica;")	// Disable triggers temporarily to avoid FK constraint issues	db := client.Driver().(*sql.DB)	// Get the underlying SQL DB		ctx := context.Background()	t.Helper()func TruncateAllTables(t *testing.T, client *ent.Client) {// TruncateAllTables removes all data from test tables}	return client	})		client.Close()		TruncateAllTables(t, client)	t.Cleanup(func() {	// Setup cleanup	require.NoError(t, err, "failed to run migrations")	err = client.Schema.Create(ctx)	ctx := context.Background()	// Run migrations	require.NoError(t, err, "failed to connect to test database")	client, err := ent.Open("postgres", dbURL)	// Open database connection	}		dbURL = "postgresql://postgres:postgres@localhost:5432/apprun_test?sslmode=disable"	if dbURL == "" {	dbURL := os.Getenv("TEST_DATABASE_URL")	// Get test database URL from environment	t.Helper()func SetupTestDB(t *testing.T) *ent.Client {// SetupTestDB creates a test database connection and runs migrations)	_ "github.com/lib/pq"	"github.com/stretchr/testify/require"	"github.com/Websoft9/apprun/core/ent"	"testing"	"os"	"fmt"