package config

import (
	"fmt"
	"io"
	"reflect"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// Generator defines the interface for configuration file generation
type Generator interface {
	// GenerateConfigExample generates config.example YAML content
	GenerateConfigExample() (string, error)

	// GenerateEnvExample generates .env.example content
	GenerateEnvExample() string

	// WriteConfigExample writes config.example to a writer
	WriteConfigExample(w io.Writer) error

	// WriteEnvExample writes .env.example to a writer
	WriteEnvExample(w io.Writer) error
}

// DefaultGenerator is the default implementation of Generator
type DefaultGenerator struct {
	registry *ConfigRegistry
}

// NewGenerator creates a new generator with the provided registry
// The registry should already have all necessary modules registered
func NewGenerator(registry *ConfigRegistry) Generator {
	return &DefaultGenerator{
		registry: registry,
	}
}

// GenerateConfigExample generates YAML with comments from registry
func (g *DefaultGenerator) GenerateConfigExample() (string, error) {
	var sb strings.Builder

	// Header
	sb.WriteString("# Configuration Example\n")
	sb.WriteString("# Auto-generated by: apprun generate config\n")
	sb.WriteString("# DO NOT use in production - customize and rename to config.yaml\n")
	sb.WriteString("\n")

	// Iterate through all registered modules
	modules := g.registry.GetAll()
	for namespace, configStruct := range modules {
		// Skip modules that only have envonly fields (like bootstrap)
		if isEnvOnlyModule(configStruct) {
			continue
		}

		sb.WriteString(fmt.Sprintf("# === %s Module ===\n", strings.ToUpper(namespace)))

		// Generate YAML for this module
		moduleYAML, err := generateModuleYAML(namespace, configStruct)
		if err != nil {
			return "", fmt.Errorf("failed to generate YAML for module '%s': %w", namespace, err)
		}

		sb.WriteString(moduleYAML)
		sb.WriteString("\n")
	}

	return sb.String(), nil
}

// GenerateEnvExample generates .env.example from envonly-tagged fields
func (g *DefaultGenerator) GenerateEnvExample() string {
	var sb strings.Builder

	sb.WriteString("# Environment Variables Example\n")
	sb.WriteString("# Auto-generated by: apprun generate config\n")
	sb.WriteString("# Copy to .env and customize for your environment\n")
	sb.WriteString("\n")
	sb.WriteString("# ============================================================================\n")
	sb.WriteString("# Operational Settings (envonly - NOT configurable via YAML)\n")
	sb.WriteString("# ============================================================================\n")
	sb.WriteString("\n")

	modules := g.registry.GetAll()
	hasEnvOnlyVars := false

	for namespace, configStruct := range modules {
		envVars := extractEnvOnlyVars(namespace, configStruct)
		if len(envVars) > 0 {
			hasEnvOnlyVars = true
			titleCaser := cases.Title(language.English)
			sb.WriteString(fmt.Sprintf("# --- %s Module ---\n", titleCaser.String(namespace)))
			for _, envVar := range envVars {
				sb.WriteString(envVar + "\n")
			}
			sb.WriteString("\n")
		}
	}

	if !hasEnvOnlyVars {
		sb.WriteString("# No envonly variables found in registered modules\n")
	}

	sb.WriteString("\n# ============================================================================\n")
	sb.WriteString("# Infrastructure Settings (can also use config files)\n")
	sb.WriteString("# ============================================================================\n")
	sb.WriteString("# Uncomment and set as needed to override config file values\n")
	sb.WriteString("# All config file settings can be overridden via environment variables\n")
	sb.WriteString("# Naming convention: UPPERCASE with underscores (e.g., database.host -> DATABASE_HOST)\n")
	sb.WriteString("\n")

	// Generate environment variables for all infrastructure modules
	for namespace, configStruct := range modules {
		// Skip envonly modules (already processed above)
		if isEnvOnlyModule(configStruct) {
			continue
		}

		infraVars := extractInfrastructureEnvVars(namespace, configStruct)
		if len(infraVars) > 0 {
			sb.WriteString(fmt.Sprintf("# --- %s Module ---\n", cases.Title(language.English).String(namespace)))
			for _, envVar := range infraVars {
				sb.WriteString(envVar + "\n")
			}
			sb.WriteString("\n")
		}
	}

	return sb.String()
}

// WriteConfigExample writes config.example to a writer
func (g *DefaultGenerator) WriteConfigExample(w io.Writer) error {
	content, err := g.GenerateConfigExample()
	if err != nil {
		return err
	}
	_, err = w.Write([]byte(content))
	return err
}

// WriteEnvExample writes .env.example to a writer
func (g *DefaultGenerator) WriteEnvExample(w io.Writer) error {
	content := g.GenerateEnvExample()
	_, err := w.Write([]byte(content))
	return err
}

// === Helper Functions ===

// generateModuleYAML generates YAML for a single module with inline comments
func generateModuleYAML(namespace string, configStruct interface{}) (string, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("%s:\n", namespace))

	// Use reflection to extract struct fields and tags
	val := reflect.ValueOf(configStruct)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)

		// Extract tags - support both yaml and mapstructure
		yamlTag := field.Tag.Get("yaml")
		if yamlTag == "" {
			yamlTag = field.Tag.Get("mapstructure") // Fallback to mapstructure
		}
		if yamlTag == "" || yamlTag == "-" {
			continue // Skip fields without yaml/mapstructure tag
		}

		// Remove omitempty and other modifiers
		yamlName := strings.Split(yamlTag, ",")[0]

		defaultValue := field.Tag.Get("default")
		validateRule := field.Tag.Get("validate")
		dbFlag := field.Tag.Get("db")

		// Generate comment with metadata
		var comments []string
		if defaultValue != "" {
			comments = append(comments, fmt.Sprintf("default: %s", defaultValue))
		}
		if validateRule != "" {
			comments = append(comments, fmt.Sprintf("validate: %s", validateRule))
		}
		if dbFlag != "" {
			comments = append(comments, fmt.Sprintf("db: %s", dbFlag))
		}

		// Write field with inline comment
		if len(comments) > 0 {
			sb.WriteString(fmt.Sprintf("  %s:  # %s\n", yamlName, strings.Join(comments, ", ")))
		} else {
			sb.WriteString(fmt.Sprintf("  %s:\n", yamlName))
		}

		// Handle nested structs recursively
		if field.Type.Kind() == reflect.Struct {
			nestedYAML := generateNestedStruct(field.Type, 4)
			sb.WriteString(nestedYAML)
		} else {
			// Write example value based on type
			fieldValue := generateExampleValue(field.Type, defaultValue)
			sb.WriteString(fmt.Sprintf("    %s\n", fieldValue))
		}
	}

	return sb.String(), nil
}

// generateNestedStruct generates YAML for nested struct fields
func generateNestedStruct(structType reflect.Type, indent int) string {
	var sb strings.Builder
	indentStr := strings.Repeat(" ", indent)

	for i := 0; i < structType.NumField(); i++ {
		field := structType.Field(i)

		// Support both yaml and mapstructure tags
		yamlTag := field.Tag.Get("yaml")
		if yamlTag == "" {
			yamlTag = field.Tag.Get("mapstructure")
		}
		if yamlTag == "" || yamlTag == "-" {
			continue
		}

		yamlName := strings.Split(yamlTag, ",")[0]
		defaultValue := field.Tag.Get("default")
		validateRule := field.Tag.Get("validate")
		dbFlag := field.Tag.Get("db")

		// Generate inline comment with metadata
		var comments []string
		if defaultValue != "" {
			comments = append(comments, fmt.Sprintf("default: %s", defaultValue))
		}
		if validateRule != "" {
			comments = append(comments, fmt.Sprintf("validate: %s", validateRule))
		}
		if dbFlag != "" {
			comments = append(comments, fmt.Sprintf("db: %s", dbFlag))
		}

		// Write field name
		sb.WriteString(fmt.Sprintf("%s%s:", indentStr, yamlName))

		if field.Type.Kind() == reflect.Struct {
			// Add comment for nested struct if metadata exists
			if len(comments) > 0 {
				sb.WriteString(fmt.Sprintf("  # %s\n", strings.Join(comments, ", ")))
			} else {
				sb.WriteString("\n")
			}
			sb.WriteString(generateNestedStruct(field.Type, indent+2))
		} else {
			// Add inline comment
			if len(comments) > 0 {
				sb.WriteString(fmt.Sprintf("  # %s\n", strings.Join(comments, ", ")))
				sb.WriteString(fmt.Sprintf("%s  ", indentStr))
			} else {
				sb.WriteString(" ")
			}
			fieldValue := generateExampleValue(field.Type, defaultValue)
			sb.WriteString(fmt.Sprintf("%s\n", fieldValue))
		}
	}

	return sb.String()
}

// generateExampleValue generates an example value based on field type and default tag
func generateExampleValue(fieldType reflect.Type, defaultValue string) string {
	// Handle pointer types
	if fieldType.Kind() == reflect.Ptr {
		fieldType = fieldType.Elem()
	}

	// Use default value if available
	if defaultValue != "" {
		// Handle special cases
		if strings.HasPrefix(defaultValue, "[") {
			// Array default value
			return fmt.Sprintf("# %s", defaultValue)
		}

		// For strings with special chars, add quotes
		if fieldType.Kind() == reflect.String && (strings.Contains(defaultValue, " ") || strings.Contains(defaultValue, ":")) {
			return fmt.Sprintf("%q", defaultValue)
		}

		return defaultValue
	}

	// Generate placeholder based on type
	switch fieldType.Kind() {
	case reflect.String:
		return "\"\"  # TODO: Set value"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return "0"
	case reflect.Bool:
		return "false"
	case reflect.Slice:
		return "[]"
	case reflect.Map:
		return "{}"
	case reflect.Struct:
		return "{}  # Nested struct"
	default:
		return "null"
	}
}

// isEnvOnlyModule checks if all fields in a module are envonly
func isEnvOnlyModule(configStruct interface{}) bool {
	val := reflect.ValueOf(configStruct)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()
	if typ.NumField() == 0 {
		return false
	}

	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)

		// If any field is NOT envonly, the module is not envonly
		envOnly := field.Tag.Get("envonly")
		if envOnly != "true" {
			return false
		}
	}

	return true
}

// extractEnvOnlyVars extracts fields with envonly:"true" tag
func extractEnvOnlyVars(namespace string, configStruct interface{}) []string {
	var vars []string

	val := reflect.ValueOf(configStruct)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)

		// Check for envonly tag
		envOnly := field.Tag.Get("envonly")
		if envOnly != "true" {
			continue
		}

		// Generate environment variable name
		jsonTag := field.Tag.Get("json")
		if jsonTag == "" || jsonTag == "-" {
			continue
		}

		jsonName := strings.Split(jsonTag, ",")[0]
		envName := strings.ToUpper(jsonName)

		// Get metadata for comment
		defaultValue := field.Tag.Get("default")

		// Build comment
		comment := fmt.Sprintf("# %s - Environment variable only (not in config files)", field.Name)
		if defaultValue != "" {
			comment += fmt.Sprintf(" [default: %s]", defaultValue)
		}

		vars = append(vars, comment, fmt.Sprintf("%s=%s", envName, defaultValue))
	}

	return vars
}

// extractInfrastructureEnvVars extracts all fields as environment variables
func extractInfrastructureEnvVars(namespace string, configStruct interface{}) []string {
	var vars []string

	val := reflect.ValueOf(configStruct)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()
	vars = extractEnvVarsFromStruct(namespace, typ, "")

	return vars
}

// extractEnvVarsFromStruct recursively extracts environment variables from struct
func extractEnvVarsFromStruct(namespace string, structType reflect.Type, prefix string) []string {
	var vars []string

	for i := 0; i < structType.NumField(); i++ {
		field := structType.Field(i)

		// Skip envonly fields (already handled)
		envOnly := field.Tag.Get("envonly")
		if envOnly == "true" {
			continue
		}

		// Get field name from mapstructure or yaml tag
		fieldTag := field.Tag.Get("mapstructure")
		if fieldTag == "" {
			fieldTag = field.Tag.Get("yaml")
		}
		if fieldTag == "" || fieldTag == "-" {
			continue
		}

		fieldName := strings.Split(fieldTag, ",")[0]

		// Build environment variable name
		var envName string
		if prefix == "" {
			envName = strings.ToUpper(namespace + "_" + fieldName)
		} else {
			envName = strings.ToUpper(prefix + "_" + fieldName)
		}

		// Handle nested structs
		if field.Type.Kind() == reflect.Struct {
			nestedVars := extractEnvVarsFromStruct(namespace, field.Type, envName)
			vars = append(vars, nestedVars...)
			continue
		}

		// Get metadata
		defaultValue := field.Tag.Get("default")
		dbFlag := field.Tag.Get("db")

		// Build comment
		comment := fmt.Sprintf("# %s", fieldName)
		if defaultValue != "" {
			comment += fmt.Sprintf(" [default: %s]", defaultValue)
		}
		if dbFlag == "false" {
			comment += " (infrastructure)"
		}

		// Format the environment variable
		vars = append(vars, comment)
		if defaultValue != "" {
			vars = append(vars, fmt.Sprintf("#%s=%s", envName, defaultValue))
		} else {
			vars = append(vars, fmt.Sprintf("#%s=", envName))
		}
	}

	return vars
}
