// Code generated by ent, DO NOT EDIT.

package configitem

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the configitem type in the database.
	Label = "configitem"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldIsDynamic holds the string denoting the is_dynamic field in the database.
	FieldIsDynamic = "is_dynamic"
	// Table holds the table name of the configitem in the database.
	Table = "configitems"
)

// Columns holds all SQL columns for configitem fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldValue,
	FieldIsDynamic,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// DefaultIsDynamic holds the default value on creation for the "is_dynamic" field.
	DefaultIsDynamic bool
)

// OrderOption defines the ordering options for the Configitem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByIsDynamic orders the results by the is_dynamic field.
func ByIsDynamic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDynamic, opts...).ToFunc()
}
