// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apprun/ent/auditlog"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AuditLogCreate is the builder for creating a AuditLog entity.
type AuditLogCreate struct {
	config
	mutation *AuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTimestamp sets the "timestamp" field.
func (_c *AuditLogCreate) SetTimestamp(v time.Time) *AuditLogCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableTimestamp(v *time.Time) *AuditLogCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetOperatorID sets the "operator_id" field.
func (_c *AuditLogCreate) SetOperatorID(v uuid.UUID) *AuditLogCreate {
	_c.mutation.SetOperatorID(v)
	return _c
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableOperatorID(v *uuid.UUID) *AuditLogCreate {
	if v != nil {
		_c.SetOperatorID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AuditLogCreate) SetAction(v string) *AuditLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *AuditLogCreate) SetTargetID(v string) *AuditLogCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableTargetID(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetTargetID(*v)
	}
	return _c
}

// SetTargetType sets the "target_type" field.
func (_c *AuditLogCreate) SetTargetType(v string) *AuditLogCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableTargetType(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetTargetType(*v)
	}
	return _c
}

// SetChanges sets the "changes" field.
func (_c *AuditLogCreate) SetChanges(v map[string]interface{}) *AuditLogCreate {
	_c.mutation.SetChanges(v)
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *AuditLogCreate) SetIPAddress(v string) *AuditLogCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableIPAddress(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *AuditLogCreate) SetUserAgent(v string) *AuditLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableUserAgent(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *AuditLogCreate) SetStatusCode(v int) *AuditLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableStatusCode(v *int) *AuditLogCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (_c *AuditLogCreate) SetResponseTimeMs(v int) *AuditLogCreate {
	_c.mutation.SetResponseTimeMs(v)
	return _c
}

// SetNillableResponseTimeMs sets the "response_time_ms" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableResponseTimeMs(v *int) *AuditLogCreate {
	if v != nil {
		_c.SetResponseTimeMs(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *AuditLogCreate) SetMethod(v string) *AuditLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableMethod(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *AuditLogCreate) SetPath(v string) *AuditLogCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillablePath(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuditLogCreate) SetID(v uuid.UUID) *AuditLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableID(v *uuid.UUID) *AuditLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AuditLogMutation object of the builder.
func (_c *AuditLogCreate) Mutation() *AuditLogMutation {
	return _c.mutation
}

// Save creates the AuditLog in the database.
func (_c *AuditLogCreate) Save(ctx context.Context) (*AuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditLogCreate) SaveX(ctx context.Context) *AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditLogCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := auditlog.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := auditlog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditLogCreate) check() error {
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "AuditLog.timestamp"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AuditLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := auditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "AuditLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := auditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuditLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := auditlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AuditLog.method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := auditlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AuditLog.path": %w`, err)}
		}
	}
	return nil
}

func (_c *AuditLogCreate) sqlSave(ctx context.Context) (*AuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditLogCreate) createSpec() (*AuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditlog.Table, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(auditlog.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.OperatorID(); ok {
		_spec.SetField(auditlog.FieldOperatorID, field.TypeUUID, value)
		_node.OperatorID = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(auditlog.FieldTargetID, field.TypeString, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(auditlog.FieldTargetType, field.TypeString, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.Changes(); ok {
		_spec.SetField(auditlog.FieldChanges, field.TypeJSON, value)
		_node.Changes = value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(auditlog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.ResponseTimeMs(); ok {
		_spec.SetField(auditlog.FieldResponseTimeMs, field.TypeInt, value)
		_node.ResponseTimeMs = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(auditlog.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(auditlog.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditLog.Create().
//		SetTimestamp(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditLogUpsert) {
//			SetTimestamp(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditLogCreate) OnConflict(opts ...sql.ConflictOption) *AuditLogUpsertOne {
	_c.conflict = opts
	return &AuditLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditLogCreate) OnConflictColumns(columns ...string) *AuditLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditLogUpsertOne{
		create: _c,
	}
}

type (
	// AuditLogUpsertOne is the builder for "upsert"-ing
	//  one AuditLog node.
	AuditLogUpsertOne struct {
		create *AuditLogCreate
	}

	// AuditLogUpsert is the "OnConflict" setter.
	AuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetOperatorID sets the "operator_id" field.
func (u *AuditLogUpsert) SetOperatorID(v uuid.UUID) *AuditLogUpsert {
	u.Set(auditlog.FieldOperatorID, v)
	return u
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateOperatorID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldOperatorID)
	return u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (u *AuditLogUpsert) ClearOperatorID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldOperatorID)
	return u
}

// SetAction sets the "action" field.
func (u *AuditLogUpsert) SetAction(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateAction() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldAction)
	return u
}

// SetTargetID sets the "target_id" field.
func (u *AuditLogUpsert) SetTargetID(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldTargetID, v)
	return u
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateTargetID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldTargetID)
	return u
}

// ClearTargetID clears the value of the "target_id" field.
func (u *AuditLogUpsert) ClearTargetID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldTargetID)
	return u
}

// SetTargetType sets the "target_type" field.
func (u *AuditLogUpsert) SetTargetType(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldTargetType, v)
	return u
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateTargetType() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldTargetType)
	return u
}

// ClearTargetType clears the value of the "target_type" field.
func (u *AuditLogUpsert) ClearTargetType() *AuditLogUpsert {
	u.SetNull(auditlog.FieldTargetType)
	return u
}

// SetChanges sets the "changes" field.
func (u *AuditLogUpsert) SetChanges(v map[string]interface{}) *AuditLogUpsert {
	u.Set(auditlog.FieldChanges, v)
	return u
}

// UpdateChanges sets the "changes" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateChanges() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldChanges)
	return u
}

// ClearChanges clears the value of the "changes" field.
func (u *AuditLogUpsert) ClearChanges() *AuditLogUpsert {
	u.SetNull(auditlog.FieldChanges)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *AuditLogUpsert) SetIPAddress(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateIPAddress() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldIPAddress)
	return u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *AuditLogUpsert) ClearIPAddress() *AuditLogUpsert {
	u.SetNull(auditlog.FieldIPAddress)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *AuditLogUpsert) SetUserAgent(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateUserAgent() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *AuditLogUpsert) ClearUserAgent() *AuditLogUpsert {
	u.SetNull(auditlog.FieldUserAgent)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *AuditLogUpsert) SetStatusCode(v int) *AuditLogUpsert {
	u.Set(auditlog.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateStatusCode() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *AuditLogUpsert) AddStatusCode(v int) *AuditLogUpsert {
	u.Add(auditlog.FieldStatusCode, v)
	return u
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *AuditLogUpsert) ClearStatusCode() *AuditLogUpsert {
	u.SetNull(auditlog.FieldStatusCode)
	return u
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (u *AuditLogUpsert) SetResponseTimeMs(v int) *AuditLogUpsert {
	u.Set(auditlog.FieldResponseTimeMs, v)
	return u
}

// UpdateResponseTimeMs sets the "response_time_ms" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateResponseTimeMs() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldResponseTimeMs)
	return u
}

// AddResponseTimeMs adds v to the "response_time_ms" field.
func (u *AuditLogUpsert) AddResponseTimeMs(v int) *AuditLogUpsert {
	u.Add(auditlog.FieldResponseTimeMs, v)
	return u
}

// ClearResponseTimeMs clears the value of the "response_time_ms" field.
func (u *AuditLogUpsert) ClearResponseTimeMs() *AuditLogUpsert {
	u.SetNull(auditlog.FieldResponseTimeMs)
	return u
}

// SetMethod sets the "method" field.
func (u *AuditLogUpsert) SetMethod(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldMethod, v)
	return u
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateMethod() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldMethod)
	return u
}

// ClearMethod clears the value of the "method" field.
func (u *AuditLogUpsert) ClearMethod() *AuditLogUpsert {
	u.SetNull(auditlog.FieldMethod)
	return u
}

// SetPath sets the "path" field.
func (u *AuditLogUpsert) SetPath(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdatePath() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldPath)
	return u
}

// ClearPath clears the value of the "path" field.
func (u *AuditLogUpsert) ClearPath() *AuditLogUpsert {
	u.SetNull(auditlog.FieldPath)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(auditlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuditLogUpsertOne) UpdateNewValues() *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(auditlog.FieldID)
		}
		if _, exists := u.create.mutation.Timestamp(); exists {
			s.SetIgnore(auditlog.FieldTimestamp)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuditLogUpsertOne) Ignore() *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditLogUpsertOne) DoNothing() *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditLogCreate.OnConflict
// documentation for more info.
func (u *AuditLogUpsertOne) Update(set func(*AuditLogUpsert)) *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperatorID sets the "operator_id" field.
func (u *AuditLogUpsertOne) SetOperatorID(v uuid.UUID) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateOperatorID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateOperatorID()
	})
}

// ClearOperatorID clears the value of the "operator_id" field.
func (u *AuditLogUpsertOne) ClearOperatorID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearOperatorID()
	})
}

// SetAction sets the "action" field.
func (u *AuditLogUpsertOne) SetAction(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateAction() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateAction()
	})
}

// SetTargetID sets the "target_id" field.
func (u *AuditLogUpsertOne) SetTargetID(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetTargetID(v)
	})
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateTargetID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateTargetID()
	})
}

// ClearTargetID clears the value of the "target_id" field.
func (u *AuditLogUpsertOne) ClearTargetID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearTargetID()
	})
}

// SetTargetType sets the "target_type" field.
func (u *AuditLogUpsertOne) SetTargetType(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetTargetType(v)
	})
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateTargetType() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateTargetType()
	})
}

// ClearTargetType clears the value of the "target_type" field.
func (u *AuditLogUpsertOne) ClearTargetType() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearTargetType()
	})
}

// SetChanges sets the "changes" field.
func (u *AuditLogUpsertOne) SetChanges(v map[string]interface{}) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetChanges(v)
	})
}

// UpdateChanges sets the "changes" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateChanges() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateChanges()
	})
}

// ClearChanges clears the value of the "changes" field.
func (u *AuditLogUpsertOne) ClearChanges() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearChanges()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *AuditLogUpsertOne) SetIPAddress(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateIPAddress() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *AuditLogUpsertOne) ClearIPAddress() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearIPAddress()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *AuditLogUpsertOne) SetUserAgent(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateUserAgent() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *AuditLogUpsertOne) ClearUserAgent() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *AuditLogUpsertOne) SetStatusCode(v int) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *AuditLogUpsertOne) AddStatusCode(v int) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateStatusCode() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *AuditLogUpsertOne) ClearStatusCode() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearStatusCode()
	})
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (u *AuditLogUpsertOne) SetResponseTimeMs(v int) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetResponseTimeMs(v)
	})
}

// AddResponseTimeMs adds v to the "response_time_ms" field.
func (u *AuditLogUpsertOne) AddResponseTimeMs(v int) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.AddResponseTimeMs(v)
	})
}

// UpdateResponseTimeMs sets the "response_time_ms" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateResponseTimeMs() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateResponseTimeMs()
	})
}

// ClearResponseTimeMs clears the value of the "response_time_ms" field.
func (u *AuditLogUpsertOne) ClearResponseTimeMs() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearResponseTimeMs()
	})
}

// SetMethod sets the "method" field.
func (u *AuditLogUpsertOne) SetMethod(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateMethod() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateMethod()
	})
}

// ClearMethod clears the value of the "method" field.
func (u *AuditLogUpsertOne) ClearMethod() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearMethod()
	})
}

// SetPath sets the "path" field.
func (u *AuditLogUpsertOne) SetPath(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdatePath() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *AuditLogUpsertOne) ClearPath() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearPath()
	})
}

// Exec executes the query.
func (u *AuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuditLogUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuditLogUpsertOne.ID is not supported by MySQL driver. Use AuditLogUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuditLogUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuditLogCreateBulk is the builder for creating many AuditLog entities in bulk.
type AuditLogCreateBulk struct {
	config
	err      error
	builders []*AuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the AuditLog entities in the database.
func (_c *AuditLogCreateBulk) Save(ctx context.Context) ([]*AuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditLogCreateBulk) SaveX(ctx context.Context) []*AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditLogUpsert) {
//			SetTimestamp(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuditLogUpsertBulk {
	_c.conflict = opts
	return &AuditLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditLogCreateBulk) OnConflictColumns(columns ...string) *AuditLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditLogUpsertBulk{
		create: _c,
	}
}

// AuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of AuditLog nodes.
type AuditLogUpsertBulk struct {
	create *AuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(auditlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuditLogUpsertBulk) UpdateNewValues() *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(auditlog.FieldID)
			}
			if _, exists := b.mutation.Timestamp(); exists {
				s.SetIgnore(auditlog.FieldTimestamp)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuditLogUpsertBulk) Ignore() *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditLogUpsertBulk) DoNothing() *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *AuditLogUpsertBulk) Update(set func(*AuditLogUpsert)) *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperatorID sets the "operator_id" field.
func (u *AuditLogUpsertBulk) SetOperatorID(v uuid.UUID) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateOperatorID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateOperatorID()
	})
}

// ClearOperatorID clears the value of the "operator_id" field.
func (u *AuditLogUpsertBulk) ClearOperatorID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearOperatorID()
	})
}

// SetAction sets the "action" field.
func (u *AuditLogUpsertBulk) SetAction(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateAction() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateAction()
	})
}

// SetTargetID sets the "target_id" field.
func (u *AuditLogUpsertBulk) SetTargetID(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetTargetID(v)
	})
}

// UpdateTargetID sets the "target_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateTargetID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateTargetID()
	})
}

// ClearTargetID clears the value of the "target_id" field.
func (u *AuditLogUpsertBulk) ClearTargetID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearTargetID()
	})
}

// SetTargetType sets the "target_type" field.
func (u *AuditLogUpsertBulk) SetTargetType(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetTargetType(v)
	})
}

// UpdateTargetType sets the "target_type" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateTargetType() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateTargetType()
	})
}

// ClearTargetType clears the value of the "target_type" field.
func (u *AuditLogUpsertBulk) ClearTargetType() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearTargetType()
	})
}

// SetChanges sets the "changes" field.
func (u *AuditLogUpsertBulk) SetChanges(v map[string]interface{}) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetChanges(v)
	})
}

// UpdateChanges sets the "changes" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateChanges() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateChanges()
	})
}

// ClearChanges clears the value of the "changes" field.
func (u *AuditLogUpsertBulk) ClearChanges() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearChanges()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *AuditLogUpsertBulk) SetIPAddress(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateIPAddress() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *AuditLogUpsertBulk) ClearIPAddress() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearIPAddress()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *AuditLogUpsertBulk) SetUserAgent(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateUserAgent() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *AuditLogUpsertBulk) ClearUserAgent() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *AuditLogUpsertBulk) SetStatusCode(v int) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *AuditLogUpsertBulk) AddStatusCode(v int) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateStatusCode() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *AuditLogUpsertBulk) ClearStatusCode() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearStatusCode()
	})
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (u *AuditLogUpsertBulk) SetResponseTimeMs(v int) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetResponseTimeMs(v)
	})
}

// AddResponseTimeMs adds v to the "response_time_ms" field.
func (u *AuditLogUpsertBulk) AddResponseTimeMs(v int) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.AddResponseTimeMs(v)
	})
}

// UpdateResponseTimeMs sets the "response_time_ms" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateResponseTimeMs() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateResponseTimeMs()
	})
}

// ClearResponseTimeMs clears the value of the "response_time_ms" field.
func (u *AuditLogUpsertBulk) ClearResponseTimeMs() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearResponseTimeMs()
	})
}

// SetMethod sets the "method" field.
func (u *AuditLogUpsertBulk) SetMethod(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateMethod() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateMethod()
	})
}

// ClearMethod clears the value of the "method" field.
func (u *AuditLogUpsertBulk) ClearMethod() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearMethod()
	})
}

// SetPath sets the "path" field.
func (u *AuditLogUpsertBulk) SetPath(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdatePath() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *AuditLogUpsertBulk) ClearPath() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearPath()
	})
}

// Exec executes the query.
func (u *AuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
