// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apprun/ent/auditlog"
	"apprun/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *AuditLogUpdate) SetOperatorID(v uuid.UUID) *AuditLogUpdate {
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableOperatorID(v *uuid.UUID) *AuditLogUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (_u *AuditLogUpdate) ClearOperatorID() *AuditLogUpdate {
	_u.mutation.ClearOperatorID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v string) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *AuditLogUpdate) SetTargetID(v string) *AuditLogUpdate {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableTargetID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *AuditLogUpdate) ClearTargetID() *AuditLogUpdate {
	_u.mutation.ClearTargetID()
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *AuditLogUpdate) SetTargetType(v string) *AuditLogUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableTargetType(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// ClearTargetType clears the value of the "target_type" field.
func (_u *AuditLogUpdate) ClearTargetType() *AuditLogUpdate {
	_u.mutation.ClearTargetType()
	return _u
}

// SetChanges sets the "changes" field.
func (_u *AuditLogUpdate) SetChanges(v map[string]interface{}) *AuditLogUpdate {
	_u.mutation.SetChanges(v)
	return _u
}

// ClearChanges clears the value of the "changes" field.
func (_u *AuditLogUpdate) ClearChanges() *AuditLogUpdate {
	_u.mutation.ClearChanges()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *AuditLogUpdate) SetIPAddress(v string) *AuditLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableIPAddress(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *AuditLogUpdate) ClearIPAddress() *AuditLogUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuditLogUpdate) SetUserAgent(v string) *AuditLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableUserAgent(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AuditLogUpdate) ClearUserAgent() *AuditLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *AuditLogUpdate) SetStatusCode(v int) *AuditLogUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableStatusCode(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *AuditLogUpdate) AddStatusCode(v int) *AuditLogUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *AuditLogUpdate) ClearStatusCode() *AuditLogUpdate {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (_u *AuditLogUpdate) SetResponseTimeMs(v int) *AuditLogUpdate {
	_u.mutation.ResetResponseTimeMs()
	_u.mutation.SetResponseTimeMs(v)
	return _u
}

// SetNillableResponseTimeMs sets the "response_time_ms" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResponseTimeMs(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetResponseTimeMs(*v)
	}
	return _u
}

// AddResponseTimeMs adds value to the "response_time_ms" field.
func (_u *AuditLogUpdate) AddResponseTimeMs(v int) *AuditLogUpdate {
	_u.mutation.AddResponseTimeMs(v)
	return _u
}

// ClearResponseTimeMs clears the value of the "response_time_ms" field.
func (_u *AuditLogUpdate) ClearResponseTimeMs() *AuditLogUpdate {
	_u.mutation.ClearResponseTimeMs()
	return _u
}

// SetMethod sets the "method" field.
func (_u *AuditLogUpdate) SetMethod(v string) *AuditLogUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableMethod(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *AuditLogUpdate) ClearMethod() *AuditLogUpdate {
	_u.mutation.ClearMethod()
	return _u
}

// SetPath sets the "path" field.
func (_u *AuditLogUpdate) SetPath(v string) *AuditLogUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillablePath(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *AuditLogUpdate) ClearPath() *AuditLogUpdate {
	_u.mutation.ClearPath()
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := auditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "AuditLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := auditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuditLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := auditlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AuditLog.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := auditlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AuditLog.path": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(auditlog.FieldOperatorID, field.TypeUUID, value)
	}
	if _u.mutation.OperatorIDCleared() {
		_spec.ClearField(auditlog.FieldOperatorID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(auditlog.FieldTargetID, field.TypeString, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(auditlog.FieldTargetID, field.TypeString)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(auditlog.FieldTargetType, field.TypeString, value)
	}
	if _u.mutation.TargetTypeCleared() {
		_spec.ClearField(auditlog.FieldTargetType, field.TypeString)
	}
	if value, ok := _u.mutation.Changes(); ok {
		_spec.SetField(auditlog.FieldChanges, field.TypeJSON, value)
	}
	if _u.mutation.ChangesCleared() {
		_spec.ClearField(auditlog.FieldChanges, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(auditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(auditlog.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.ResponseTimeMs(); ok {
		_spec.SetField(auditlog.FieldResponseTimeMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseTimeMs(); ok {
		_spec.AddField(auditlog.FieldResponseTimeMs, field.TypeInt, value)
	}
	if _u.mutation.ResponseTimeMsCleared() {
		_spec.ClearField(auditlog.FieldResponseTimeMs, field.TypeInt)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(auditlog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(auditlog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(auditlog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(auditlog.FieldPath, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetOperatorID sets the "operator_id" field.
func (_u *AuditLogUpdateOne) SetOperatorID(v uuid.UUID) *AuditLogUpdateOne {
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableOperatorID(v *uuid.UUID) *AuditLogUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (_u *AuditLogUpdateOne) ClearOperatorID() *AuditLogUpdateOne {
	_u.mutation.ClearOperatorID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v string) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *AuditLogUpdateOne) SetTargetID(v string) *AuditLogUpdateOne {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableTargetID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *AuditLogUpdateOne) ClearTargetID() *AuditLogUpdateOne {
	_u.mutation.ClearTargetID()
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *AuditLogUpdateOne) SetTargetType(v string) *AuditLogUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableTargetType(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// ClearTargetType clears the value of the "target_type" field.
func (_u *AuditLogUpdateOne) ClearTargetType() *AuditLogUpdateOne {
	_u.mutation.ClearTargetType()
	return _u
}

// SetChanges sets the "changes" field.
func (_u *AuditLogUpdateOne) SetChanges(v map[string]interface{}) *AuditLogUpdateOne {
	_u.mutation.SetChanges(v)
	return _u
}

// ClearChanges clears the value of the "changes" field.
func (_u *AuditLogUpdateOne) ClearChanges() *AuditLogUpdateOne {
	_u.mutation.ClearChanges()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *AuditLogUpdateOne) SetIPAddress(v string) *AuditLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableIPAddress(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *AuditLogUpdateOne) ClearIPAddress() *AuditLogUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuditLogUpdateOne) SetUserAgent(v string) *AuditLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableUserAgent(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AuditLogUpdateOne) ClearUserAgent() *AuditLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *AuditLogUpdateOne) SetStatusCode(v int) *AuditLogUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableStatusCode(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *AuditLogUpdateOne) AddStatusCode(v int) *AuditLogUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *AuditLogUpdateOne) ClearStatusCode() *AuditLogUpdateOne {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetResponseTimeMs sets the "response_time_ms" field.
func (_u *AuditLogUpdateOne) SetResponseTimeMs(v int) *AuditLogUpdateOne {
	_u.mutation.ResetResponseTimeMs()
	_u.mutation.SetResponseTimeMs(v)
	return _u
}

// SetNillableResponseTimeMs sets the "response_time_ms" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResponseTimeMs(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResponseTimeMs(*v)
	}
	return _u
}

// AddResponseTimeMs adds value to the "response_time_ms" field.
func (_u *AuditLogUpdateOne) AddResponseTimeMs(v int) *AuditLogUpdateOne {
	_u.mutation.AddResponseTimeMs(v)
	return _u
}

// ClearResponseTimeMs clears the value of the "response_time_ms" field.
func (_u *AuditLogUpdateOne) ClearResponseTimeMs() *AuditLogUpdateOne {
	_u.mutation.ClearResponseTimeMs()
	return _u
}

// SetMethod sets the "method" field.
func (_u *AuditLogUpdateOne) SetMethod(v string) *AuditLogUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableMethod(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *AuditLogUpdateOne) ClearMethod() *AuditLogUpdateOne {
	_u.mutation.ClearMethod()
	return _u
}

// SetPath sets the "path" field.
func (_u *AuditLogUpdateOne) SetPath(v string) *AuditLogUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillablePath(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *AuditLogUpdateOne) ClearPath() *AuditLogUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := auditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "AuditLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := auditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuditLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := auditlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AuditLog.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := auditlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AuditLog.path": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(auditlog.FieldOperatorID, field.TypeUUID, value)
	}
	if _u.mutation.OperatorIDCleared() {
		_spec.ClearField(auditlog.FieldOperatorID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(auditlog.FieldTargetID, field.TypeString, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(auditlog.FieldTargetID, field.TypeString)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(auditlog.FieldTargetType, field.TypeString, value)
	}
	if _u.mutation.TargetTypeCleared() {
		_spec.ClearField(auditlog.FieldTargetType, field.TypeString)
	}
	if value, ok := _u.mutation.Changes(); ok {
		_spec.SetField(auditlog.FieldChanges, field.TypeJSON, value)
	}
	if _u.mutation.ChangesCleared() {
		_spec.ClearField(auditlog.FieldChanges, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(auditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(auditlog.FieldStatusCode, field.TypeInt)
	}
	if value, ok := _u.mutation.ResponseTimeMs(); ok {
		_spec.SetField(auditlog.FieldResponseTimeMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseTimeMs(); ok {
		_spec.AddField(auditlog.FieldResponseTimeMs, field.TypeInt, value)
	}
	if _u.mutation.ResponseTimeMsCleared() {
		_spec.ClearField(auditlog.FieldResponseTimeMs, field.TypeInt)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(auditlog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(auditlog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(auditlog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(auditlog.FieldPath, field.TypeString)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
