// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apprun/ent/configitem"
	"apprun/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConfigitemUpdate is the builder for updating Configitem entities.
type ConfigitemUpdate struct {
	config
	hooks    []Hook
	mutation *ConfigitemMutation
}

// Where appends a list predicates to the ConfigitemUpdate builder.
func (_u *ConfigitemUpdate) Where(ps ...predicate.Configitem) *ConfigitemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *ConfigitemUpdate) SetKey(v string) *ConfigitemUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ConfigitemUpdate) SetNillableKey(v *string) *ConfigitemUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ConfigitemUpdate) SetValue(v string) *ConfigitemUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ConfigitemUpdate) SetNillableValue(v *string) *ConfigitemUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetIsDynamic sets the "is_dynamic" field.
func (_u *ConfigitemUpdate) SetIsDynamic(v bool) *ConfigitemUpdate {
	_u.mutation.SetIsDynamic(v)
	return _u
}

// SetNillableIsDynamic sets the "is_dynamic" field if the given value is not nil.
func (_u *ConfigitemUpdate) SetNillableIsDynamic(v *bool) *ConfigitemUpdate {
	if v != nil {
		_u.SetIsDynamic(*v)
	}
	return _u
}

// Mutation returns the ConfigitemMutation object of the builder.
func (_u *ConfigitemUpdate) Mutation() *ConfigitemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConfigitemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigitemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConfigitemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigitemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigitemUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := configitem.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Configitem.key": %w`, err)}
		}
	}
	return nil
}

func (_u *ConfigitemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configitem.Table, configitem.Columns, sqlgraph.NewFieldSpec(configitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(configitem.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(configitem.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDynamic(); ok {
		_spec.SetField(configitem.FieldIsDynamic, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConfigitemUpdateOne is the builder for updating a single Configitem entity.
type ConfigitemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConfigitemMutation
}

// SetKey sets the "key" field.
func (_u *ConfigitemUpdateOne) SetKey(v string) *ConfigitemUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ConfigitemUpdateOne) SetNillableKey(v *string) *ConfigitemUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ConfigitemUpdateOne) SetValue(v string) *ConfigitemUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ConfigitemUpdateOne) SetNillableValue(v *string) *ConfigitemUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetIsDynamic sets the "is_dynamic" field.
func (_u *ConfigitemUpdateOne) SetIsDynamic(v bool) *ConfigitemUpdateOne {
	_u.mutation.SetIsDynamic(v)
	return _u
}

// SetNillableIsDynamic sets the "is_dynamic" field if the given value is not nil.
func (_u *ConfigitemUpdateOne) SetNillableIsDynamic(v *bool) *ConfigitemUpdateOne {
	if v != nil {
		_u.SetIsDynamic(*v)
	}
	return _u
}

// Mutation returns the ConfigitemMutation object of the builder.
func (_u *ConfigitemUpdateOne) Mutation() *ConfigitemMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConfigitemUpdate builder.
func (_u *ConfigitemUpdateOne) Where(ps ...predicate.Configitem) *ConfigitemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConfigitemUpdateOne) Select(field string, fields ...string) *ConfigitemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Configitem entity.
func (_u *ConfigitemUpdateOne) Save(ctx context.Context) (*Configitem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigitemUpdateOne) SaveX(ctx context.Context) *Configitem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConfigitemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigitemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigitemUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := configitem.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Configitem.key": %w`, err)}
		}
	}
	return nil
}

func (_u *ConfigitemUpdateOne) sqlSave(ctx context.Context) (_node *Configitem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configitem.Table, configitem.Columns, sqlgraph.NewFieldSpec(configitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Configitem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, configitem.FieldID)
		for _, f := range fields {
			if !configitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != configitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(configitem.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(configitem.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDynamic(); ok {
		_spec.SetField(configitem.FieldIsDynamic, field.TypeBool, value)
	}
	_node = &Configitem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
