// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apprun/ent/configitem"
	"apprun/ent/schema"
	"apprun/ent/servers"
	"apprun/ent/users"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	configitemFields := schema.Configitem{}.Fields()
	_ = configitemFields
	// configitemDescKey is the schema descriptor for key field.
	configitemDescKey := configitemFields[0].Descriptor()
	// configitem.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	configitem.KeyValidator = configitemDescKey.Validators[0].(func(string) error)
	// configitemDescIsDynamic is the schema descriptor for is_dynamic field.
	configitemDescIsDynamic := configitemFields[2].Descriptor()
	// configitem.DefaultIsDynamic holds the default value on creation for the is_dynamic field.
	configitem.DefaultIsDynamic = configitemDescIsDynamic.Default.(bool)
	// configitemDescCreatedAt is the schema descriptor for created_at field.
	configitemDescCreatedAt := configitemFields[4].Descriptor()
	// configitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	configitem.DefaultCreatedAt = configitemDescCreatedAt.Default.(func() time.Time)
	// configitemDescUpdatedAt is the schema descriptor for updated_at field.
	configitemDescUpdatedAt := configitemFields[5].Descriptor()
	// configitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	configitem.DefaultUpdatedAt = configitemDescUpdatedAt.Default.(func() time.Time)
	// configitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	configitem.UpdateDefaultUpdatedAt = configitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	serversFields := schema.Servers{}.Fields()
	_ = serversFields
	// serversDescName is the schema descriptor for name field.
	serversDescName := serversFields[1].Descriptor()
	// servers.NameValidator is a validator for the "name" field. It is called by the builders before save.
	servers.NameValidator = serversDescName.Validators[0].(func(string) error)
	usersFields := schema.Users{}.Fields()
	_ = usersFields
	// usersDescName is the schema descriptor for name field.
	usersDescName := usersFields[1].Descriptor()
	// users.NameValidator is a validator for the "name" field. It is called by the builders before save.
	users.NameValidator = usersDescName.Validators[0].(func(string) error)
}
