// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apprun/ent/servers"
	"apprun/ent/users"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Servers is the model entity for the Servers schema.
type Servers struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServersQuery when eager-loading is set.
	Edges         ServersEdges `json:"edges"`
	users_servers *int
	selectValues  sql.SelectValues
}

// ServersEdges holds the relations/edges for other nodes in the graph.
type ServersEdges struct {
	// Owner holds the value of the owner edge.
	Owner *Users `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServersEdges) OwnerOrErr() (*Users, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: users.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Servers) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case servers.FieldID:
			values[i] = new(sql.NullInt64)
		case servers.FieldName, servers.FieldIP:
			values[i] = new(sql.NullString)
		case servers.ForeignKeys[0]: // users_servers
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Servers fields.
func (_m *Servers) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case servers.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case servers.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case servers.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case servers.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field users_servers", value)
			} else if value.Valid {
				_m.users_servers = new(int)
				*_m.users_servers = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Servers.
// This includes values selected through modifiers, order, etc.
func (_m *Servers) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Servers entity.
func (_m *Servers) QueryOwner() *UsersQuery {
	return NewServersClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this Servers.
// Note that you need to call Servers.Unwrap() before calling this method if this Servers
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Servers) Update() *ServersUpdateOne {
	return NewServersClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Servers entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Servers) Unwrap() *Servers {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Servers is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Servers) String() string {
	var builder strings.Builder
	builder.WriteString("Servers(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteByte(')')
	return builder.String()
}

// ServersSlice is a parsable slice of Servers.
type ServersSlice []*Servers
