// Code generated by ent, DO NOT EDIT.

package ent

import (
	"apprun/ent/predicate"
	"apprun/ent/servers"
	"apprun/ent/users"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServersUpdate is the builder for updating Servers entities.
type ServersUpdate struct {
	config
	hooks    []Hook
	mutation *ServersMutation
}

// Where appends a list predicates to the ServersUpdate builder.
func (_u *ServersUpdate) Where(ps ...predicate.Servers) *ServersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ServersUpdate) SetName(v string) *ServersUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServersUpdate) SetNillableName(v *string) *ServersUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *ServersUpdate) SetIP(v string) *ServersUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *ServersUpdate) SetNillableIP(v *string) *ServersUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the Users entity by ID.
func (_u *ServersUpdate) SetOwnerID(id int) *ServersUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the Users entity.
func (_u *ServersUpdate) SetOwner(v *Users) *ServersUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ServersMutation object of the builder.
func (_u *ServersUpdate) Mutation() *ServersMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Users entity.
func (_u *ServersUpdate) ClearOwner() *ServersUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServersUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServersUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := servers.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Servers.name": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Servers.owner"`)
	}
	return nil
}

func (_u *ServersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servers.Table, servers.Columns, sqlgraph.NewFieldSpec(servers.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(servers.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(servers.FieldIP, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servers.OwnerTable,
			Columns: []string{servers.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servers.OwnerTable,
			Columns: []string{servers.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServersUpdateOne is the builder for updating a single Servers entity.
type ServersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServersMutation
}

// SetName sets the "name" field.
func (_u *ServersUpdateOne) SetName(v string) *ServersUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServersUpdateOne) SetNillableName(v *string) *ServersUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *ServersUpdateOne) SetIP(v string) *ServersUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *ServersUpdateOne) SetNillableIP(v *string) *ServersUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the Users entity by ID.
func (_u *ServersUpdateOne) SetOwnerID(id int) *ServersUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the Users entity.
func (_u *ServersUpdateOne) SetOwner(v *Users) *ServersUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ServersMutation object of the builder.
func (_u *ServersUpdateOne) Mutation() *ServersMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Users entity.
func (_u *ServersUpdateOne) ClearOwner() *ServersUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the ServersUpdate builder.
func (_u *ServersUpdateOne) Where(ps ...predicate.Servers) *ServersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServersUpdateOne) Select(field string, fields ...string) *ServersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Servers entity.
func (_u *ServersUpdateOne) Save(ctx context.Context) (*Servers, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServersUpdateOne) SaveX(ctx context.Context) *Servers {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServersUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := servers.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Servers.name": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Servers.owner"`)
	}
	return nil
}

func (_u *ServersUpdateOne) sqlSave(ctx context.Context) (_node *Servers, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servers.Table, servers.Columns, sqlgraph.NewFieldSpec(servers.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Servers.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, servers.FieldID)
		for _, f := range fields {
			if !servers.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != servers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(servers.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(servers.FieldIP, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servers.OwnerTable,
			Columns: []string{servers.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   servers.OwnerTable,
			Columns: []string{servers.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Servers{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
