// i18n-extract: 扫描代码提取翻译键
// Usage: go run scripts/i18n-extract.go -source=./core -output=./core/locales/template.toml
//go:build ignore
// +build ignore

package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var (
	sourceDir  = flag.String("source", "./core", "Source code directory")
	outputFile = flag.String("output", "./core/locales/template.toml", "Output template file")
)

func main() {
	flag.Parse()

	fmt.Printf("🔍 Scanning %s for translation keys...\n", *sourceDir)

	// 收集所有翻译键
	keys := make(map[string]bool)

	err := filepath.Walk(*sourceDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// 跳过目录和非 Go 文件
		if info.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}

		// 跳过测试文件和生成的代码
		if strings.HasSuffix(path, "_test.go") || strings.Contains(path, "/ent/") {
			return nil
		}

		// 解析文件
		fset := token.NewFileSet()
		node, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			fmt.Printf("⚠️  Failed to parse %s: %v\n", path, err)
			return nil
		}

		// 遍历 AST 查找翻译函数调用
		ast.Inspect(node, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}

			// 查找 i18n.Translate, i18n.TranslateContext
			var funcName string
			switch fun := call.Fun.(type) {
			case *ast.SelectorExpr:
				if ident, ok := fun.X.(*ast.Ident); ok {
					if ident.Name == "i18n" {
						funcName = fun.Sel.Name
					}
				}
			}

			if funcName != "Translate" && funcName != "TranslateContext" {
				return true
			}

			// 提取messageID参数
			// Translate(lang, messageID, data) - messageID是索引1
			// TranslateContext(ctx, messageID, data) - messageID是索引1
			argIndex := 1

			if len(call.Args) <= argIndex {
				return true
			}

			// 提取字符串字面量
			if lit, ok := call.Args[argIndex].(*ast.BasicLit); ok && lit.Kind == token.STRING {
				key := strings.Trim(lit.Value, `"`)
				keys[key] = true
			}

			return true
		})

		return nil
	})

	if err != nil {
		fmt.Printf("❌ Error: %v\n", err)
		os.Exit(1)
	}

	// 排序键
	var sortedKeys []string
	for key := range keys {
		sortedKeys = append(sortedKeys, key)
	}
	sort.Strings(sortedKeys)

	fmt.Printf("✅ Found %d translation keys\n", len(sortedKeys))

	// 生成 TOML 模板
	if err := generateTemplate(sortedKeys); err != nil {
		fmt.Printf("❌ Failed to generate template: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ Template saved to %s\n", *outputFile)
}

func generateTemplate(keys []string) error {
	f, err := os.Create(*outputFile)
	if err != nil {
		return err
	}
	defer f.Close()

	f.WriteString("# Auto-generated translation template\n")
	f.WriteString("# Generated by: go run scripts/i18n-extract.go\n\n")

	for _, key := range keys {
		f.WriteString(fmt.Sprintf("[%s]\n", key))
		f.WriteString(fmt.Sprintf("other = \"%s\"\n\n", key)) // Placeholder
	}

	return nil
}
