// Package main generates config/config.example from registered module configurations
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"apprun/internal/jwt"
	"apprun/modules/config"
	"apprun/pkg/i18n"
	"apprun/pkg/logger"
	"apprun/pkg/server"
)

func main() {
	// Bootstrap Registry: Explicitly register all business modules
	// (simulating main.go registration)
	registry := config.NewRegistry()

	// Register business modules
	if err := registry.Register("logger", &logger.Config{}); err != nil {
		fatal("Failed to register logger: %v", err)
	}
	if err := registry.Register("i18n", &i18n.Config{}); err != nil {
		fatal("Failed to register i18n: %v", err)
	}
	if err := registry.Register("jwt", &jwt.Config{}); err != nil {
		fatal("Failed to register jwt: %v", err)
	}
	if err := registry.Register("server", &server.Config{}); err != nil {
		fatal("Failed to register server: %v", err)
	}

	// Note: Database module is NOT registered (bootstrap circular dependency)

	// Generate config.example
	output, err := generateConfigExample(registry)
	if err != nil {
		fatal("Failed to generate config: %v", err)
	}

	// Write to config/config.example
	outputPath := filepath.Join("config", "config.example")
	// #nosec G306 -- config.example is an example file, 0644 is appropriate for documentation
	if err := os.WriteFile(outputPath, []byte(output), 0644); err != nil {
		fatal("Failed to write file: %v", err)
	}

	fmt.Printf("✅ Successfully generated %s\n", outputPath)
	fmt.Printf("   Registered modules: %d\n", registry.Count())
}

// generateConfigExample generates YAML with comments from registry
func generateConfigExample(registry *config.ConfigRegistry) (string, error) {
	var sb strings.Builder

	// Header
	sb.WriteString("# Configuration Example\n")
	sb.WriteString("# Auto-generated by: make config-example\n")
	sb.WriteString("# DO NOT use in production - customize and rename to config.yaml\n")
	sb.WriteString("\n")

	// Iterate through all registered modules
	modules := registry.GetAll()
	for namespace, configStruct := range modules {
		sb.WriteString(fmt.Sprintf("# === %s Module ===\n", strings.ToUpper(namespace)))

		// Generate YAML for this module
		moduleYAML, err := generateModuleYAML(namespace, configStruct)
		if err != nil {
			return "", fmt.Errorf("failed to generate YAML for module '%s': %w", namespace, err)
		}

		sb.WriteString(moduleYAML)
		sb.WriteString("\n")
	}

	return sb.String(), nil
}

// generateModuleYAML generates YAML for a single module with inline comments
func generateModuleYAML(namespace string, configStruct interface{}) (string, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("%s:\n", namespace))

	// Use reflection to extract struct fields and tags
	val := reflect.ValueOf(configStruct)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	typ := val.Type()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)

		// Extract tags
		yamlTag := field.Tag.Get("yaml")
		if yamlTag == "" || yamlTag == "-" {
			continue // Skip fields without yaml tag
		}

		// Remove omitempty and other modifiers
		yamlName := strings.Split(yamlTag, ",")[0]

		defaultValue := field.Tag.Get("default")
		validateRule := field.Tag.Get("validate")
		dbFlag := field.Tag.Get("db")

		// Generate comment with metadata
		var comments []string
		if defaultValue != "" {
			comments = append(comments, fmt.Sprintf("default: %s", defaultValue))
		}
		if validateRule != "" {
			comments = append(comments, fmt.Sprintf("validate: %s", validateRule))
		}
		if dbFlag != "" {
			comments = append(comments, fmt.Sprintf("db: %s", dbFlag))
		}

		// Write field with inline comment
		if len(comments) > 0 {
			sb.WriteString(fmt.Sprintf("  %s:  # %s\n", yamlName, strings.Join(comments, ", ")))
		} else {
			sb.WriteString(fmt.Sprintf("  %s:\n", yamlName))
		}

		// Handle nested structs recursively
		if field.Type.Kind() == reflect.Struct {
			nestedYAML := generateNestedStruct(field.Type, 4)
			sb.WriteString(nestedYAML)
		} else {
			// Write example value based on type
			fieldValue := generateExampleValue(field.Type, defaultValue)
			sb.WriteString(fmt.Sprintf("    %s\n", fieldValue))
		}
	}

	return sb.String(), nil
}

// generateNestedStruct generates YAML for nested struct fields
func generateNestedStruct(structType reflect.Type, indent int) string {
	var sb strings.Builder
	indentStr := strings.Repeat(" ", indent)

	for i := 0; i < structType.NumField(); i++ {
		field := structType.Field(i)

		yamlTag := field.Tag.Get("yaml")
		if yamlTag == "" || yamlTag == "-" {
			continue
		}

		yamlName := strings.Split(yamlTag, ",")[0]
		defaultValue := field.Tag.Get("default")

		sb.WriteString(fmt.Sprintf("%s%s:", indentStr, yamlName))

		if field.Type.Kind() == reflect.Struct {
			sb.WriteString("\n")
			sb.WriteString(generateNestedStruct(field.Type, indent+2))
		} else {
			fieldValue := generateExampleValue(field.Type, defaultValue)
			sb.WriteString(fmt.Sprintf(" %s\n", fieldValue))
		}
	}

	return sb.String()
} // generateExampleValue generates an example value based on field type and default tag
func generateExampleValue(fieldType reflect.Type, defaultValue string) string {
	// Handle pointer types
	if fieldType.Kind() == reflect.Ptr {
		fieldType = fieldType.Elem()
	}

	// Use default value if available
	if defaultValue != "" {
		// Handle special cases
		if strings.HasPrefix(defaultValue, "[") {
			// Array default value
			return fmt.Sprintf("# %s", defaultValue)
		}

		// For strings with special chars, add quotes
		if fieldType.Kind() == reflect.String && (strings.Contains(defaultValue, " ") || strings.Contains(defaultValue, ":")) {
			return fmt.Sprintf("%q", defaultValue)
		}

		return defaultValue
	}

	// Generate placeholder based on type
	switch fieldType.Kind() {
	case reflect.String:
		return "\"\"  # TODO: Set value"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return "0"
	case reflect.Bool:
		return "false"
	case reflect.Slice:
		return "[]"
	case reflect.Map:
		return "{}"
	case reflect.Struct:
		return "{}  # Nested struct"
	default:
		return "null"
	}
}

// fatal prints error and exits
func fatal(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "❌ ERROR: "+format+"\n", args...)
	os.Exit(1)
}
